dist: bionic

language: python

python:
- '3.6'
- '3.7'
- '3.8'

stages:
  - lint
  - test
  - deploy

env:
  matrix:
    - DJANGO_VERSION=2.2.*
    - DJANGO_VERSION=3.0.*
    - DJANGO_VERSION=dev

install:
- python setup.py install
- pip install coverage codecov
- if [[ $DJANGO_VERSION == dev ]]; then
  pip install -e git+https://github.com/django/django@master#egg=django;
  else
  pip install Django==$DJANGO_VERSION -U;
  fi

script:
- coverage run --source=template_model ./manage.py test

after_success:
  - codecov

jobs:
  allow_failures:
    - env: DJANGO_VERSION=dev

  include:
    - stage: lint
      install:
        - pip3 install flake8
      script:
        - flake8 template_model
      after_success: skip

    - stage: deploy
      install: skip
      before_script: skip
      script: skip
      deploy:
        stage: deploy
        skip_cleanup: true
        provider: pypi
        user: "$PYPI_USER"
        password:
          secure: r8MGNrhecisTRmgd60Z6z08R4aQFfmUkEPLCZ4qmMkwmOvAs1hLLieQuJxO47pT3l5H9tgwBkutL6JthVsU7scykAh8LnI7/7sgoVsF6maxdzKGgoY/PZwv21rFMnc+sSpHEWutEm96NBZGw1hwoMp4rtS0/2moVqfn8h+IxI6w519Xeh/QZRR2HqykVl0HbMHGgUdu7ePELErqFYbcRV18+WHGdhj5S5Kihhw9zELbnnoLOlm43mjzVdA75RVhOs6s4xv6CGmAILnqmasvo6PHguGeBS2B3Nk7qyo1M08D6/bPVdSTnaCAP3zqOKsvGLqRbwFRygpYeIpa5QRdKbFSaktIBxhOROdsRGzFcYzUgiAwDVmXyTzwUVxT2UJ90m4keA3nlu42LJskM3O5LKXQNwTMYmsZ6qn2iSoU7Qp31Is+nAJcl1kEJUOgKgrNd7rJ2hECVhRJc9hhVfX+vQO7jckqx1GI/es6PskkyjL7QwhfqtP1cuy0GSSHdTM+3UfKL0iFt6G4xLkmnMwuV1qHzshgmfl9RY3PYzb/bDn1Yp5LPlxwU2D/5b2dVTHDMJLb4n1+oF7GaYDzzYnGqcJaogNtzwJUTCRj9c916CO+4OvzuusLM+XQk0Yyqs0Ss3UqdNVfF0d3RezaLy/H7Vr+TKSNivxplx4jz3bJFFsg=
        on:
          tags: true
