# Generated by Django 2.2.4 on 2019-09-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_model', '0003_remove_template_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_file',
            field=models.FileField(upload_to='template_model'),
        ),
    ]
