# Generated by Django 3.0a1 on 2019-09-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_model', '0004_auto_20190916_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
